return {
	"tribela/transparent.nvim",
	event = "VimEnter",
	config = true,
	auto = true,
	opts = {
		extra_groups = {
			"Float",
			"FloatBorder",
			"LspDiagnosticsFloatingError",
			"LspDiagnosticsFloatingHint",
			"LspDiagnosticsFloatingInformation",
			"LspDiagnosticsFloatingWarning ",
			"LspDiagnosticsSignError",
			"LspDiagnosticsSignHint",
			"LspDiagnosticsSignInformation",
			"LspDiagnosticsSignWarning",
			"LspReferenceRead",
			"LspReferenceText",
			"LspReferenceWrite",
			"NormalFloat",
			"NvimFloat",
			"NvimTreeLspDiagnosticsError",
			"NvimTreeLspDiagnosticsHint",
			"NvimTreeLspDiagnosticsInformation",
			"NvimTreeLspDiagnosticsWarning",
			"NvimTreeSignColumn",
			"Pmenu",
			"SignColumn",
		},
	},
}
