#!/bin/bash

ACTION=$1
INTERVAL=$2

SINK="Master"
MAX_ALLOWED_VOLUME=120

function get_sink_volume {
	pactl list sinks | grep '^[[:space:]]Volume:' | \
    head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

case $ACTION in
	UP)
		if [ $(get_sink_volume) -lt $MAX_ALLOWED_VOLUME ]
		then
			pactl set-sink-volume @DEFAULT_SINK@ +$INTERVAL%
		fi
		;;

	DOWN)
		pactl set-sink-volume @DEFAULT_SINK@ -$INTERVAL%
		;;

	MUTE)
		pactl set-sink-mute @DEFAULT_SINK@ toggle
		;;

esac
