#!/bin/bash

# pactl-wrapper

# This script wraps the pactl volume setting feature,
# and prevents the volume level from shooting past a max allowed volume.

ACTION=$1
INTERVAL=$2

DEFAULT_MAX_LEVEL=110
MAX_ALLOWED_LEVEL=${MAX_ALLOWED_VOLUME:-$DEFAULT_MAX_LEVEL}

function get_running_sink_volume {
	pactl list sinks\
		| grep -A 8 'State: RUNNING'\
		| tail -n 1\
		| sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'
}

case $ACTION in
	UP)
		CURRENT_VOLUME=$(get_running_sink_volume)

		if [ $CURRENT_VOLUME -lt $MAX_ALLOWED_LEVEL ]
		then
			if [ $(($CURRENT_VOLUME + $INTERVAL)) -gt $MAX_ALLOWED_LEVEL ]
			then
				# i.e. if current volume + requested interval increase is
				# above allowed max, set the volume to the max.
				pactl set-sink-volume @DEFAULT_SINK@ $MAX_ALLOWED_LEVEL%

			else
				pactl set-sink-volume @DEFAULT_SINK@ +$INTERVAL%
			fi
		fi
		;;

	DOWN)
		pactl set-sink-volume @DEFAULT_SINK@ -$INTERVAL%
		;;

	TOGGLE_MUTE)
		pactl set-sink-mute @DEFAULT_SINK@ toggle
		;;
esac
